[tool.poetry]
name = "quickweb"
version = "0.1.0"
description = ""
authors = ["Andrew Downing <andrew.c.downing@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
WebOb = "^1.8.7"
gunicorn = "^20.1.0"
parse = "^1.19.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
